version: "3.9"

services:
  # Autenticación y Seguridad
  auth:
    build: ./microservices/auth
    container_name: auth_service
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@auth_db:5432/auth_db
    depends_on:
      - auth_db

  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  # Usuarios y Pasajeros
  users:
    build: ./microservices/users
    container_name: users_service
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@users_db:5432/users_db
    depends_on:
      - users_db

  users_db:
    image: postgres:15
    container_name: users_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5434:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

  # Conductores
  drivers:
    build: ./microservices/drivers
    container_name: drivers_service
    ports:
      - "3003:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@drivers_db:5432/drivers_db
    depends_on:
      - drivers_db

  drivers_db:
    image: postgres:15
    container_name: drivers_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drivers_db
    ports:
      - "5435:5432"
    volumes:
      - drivers_data:/var/lib/postgresql/data

  # Flota
  fleet:
    build: ./microservices/fleet
    container_name: fleet_service
    ports:
      - "3004:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@fleet_db:5432/fleet_db
    depends_on:
      - fleet_db

  fleet_db:
    image: postgres:15
    container_name: fleet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleet_db
    ports:
      - "5436:5432"
    volumes:
      - fleet_data:/var/lib/postgresql/data

  # Telemetría
  telemetry:
    build: ./microservices/telemetry
    container_name: telemetry_service
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@telemetry_db:5432/telemetry_db
    depends_on:
      - telemetry_db

  telemetry_db:
    image: postgres:15
    container_name: telemetry_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetry_db
    ports:
      - "5437:5432"
    volumes:
      - telemetry_data:/var/lib/postgresql/data

  # Pagos y Recargas
  payments:
    build: ./microservices/payments
    container_name: payments_service
    ports:
      - "3006:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@payments_db:5432/payments_db
    depends_on:
      - payments_db

  payments_db:
    image: postgres:15
    container_name: payments_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5438:5432"
    volumes:
      - payments_data:/var/lib/postgresql/data

  # Reportes y Analítica
  reports:
    build: ./microservices/reports
    container_name: reports_service
    ports:
      - "3007:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@reports_db:5432/reports_db
    depends_on:
      - reports_db

  reports_db:
    image: postgres:15
    container_name: reports_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reports_db
    ports:
      - "5439:5432"
    volumes:
      - reports_data:/var/lib/postgresql/data

volumes:
  auth_data:
  users_data:
  drivers_data:
  fleet_data:
  telemetry_data:
  payments_data:
  reports_data:
