apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - args:
            - sh
            - -c
            - npx prisma migrate deploy && npx ts-node prisma/seed.ts && npm run start:dev
          env:
            - name: DATABASE_URL
              value: postgresql://user:pass@db-auth:5432/auth
            - name: JWT_SECRET
              value: if-at-first-you-don't-succeed-dust-yourself-off-and-try-again
          image: auth:latest              
          imagePullPolicy: Never 
          name: auth
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
