apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: db-auth
  name: db-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-auth
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: db-auth
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: auth
            - name: POSTGRES_PASSWORD
              value: pass
            - name: POSTGRES_USER
              value: user
          image: postgres:16
          livenessProbe:
              exec:
                command:
                  - sh
                  - -c
                  - pg_isready -U user -d auth
              failureThreshold: 5
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
          name: db-auth
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
