apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: telemetry
  name: telemetry
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
    - name: "50052"
      port: 50052
      targetPort: 50052
  selector:
    io.kompose.service: telemetry
