apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: telemetry
  name: telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telemetry
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: telemetry
    spec:
      containers:
        - args:
            - npm
            - run
            - start:dev
          env:
            - name: MONGODB_URI
              value: mongodb://admin:pass@mongodb:27017/telemetry?authSource=admin
            - name: PORT
              value: "3002"
          image: telemetry:latest
          imagePullPolicy: Never
          name: telemetry
          ports:
            - containerPort: 3002
              protocol: TCP
            - containerPort: 50052
              protocol: TCP
      restartPolicy: Always
