apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: users
  name: users
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "50051"
      port: 50051
      targetPort: 50051
  selector:
    io.kompose.service: users
