apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: users
    spec:
      containers:
        - args:
            - sh
            - -c
            - npx prisma migrate deploy && npm run start:dev
          env:
            - name: DATABASE_URL
              value: postgresql://user:pass@db-users:5432/db_users
          image: users:latest
          imagePullPolicy: Never
          name: users
          ports:
            - containerPort: 3001
              protocol: TCP
            - containerPort: 50051
              protocol: TCP
      restartPolicy: Always
